POST http://localhost:3001/auth/register 
Content-Type: application/json

{
   "username":"Mydawg",
   "password":"socool1234"
}

###
POST http://localhost:3001/auth/login
Content-Type: application/json

{
   "username":"Mydawg",
   "password":"socool1234"
}

###

POST http://localhost:3001/recipes
Content-Type: application/json

{
   "name":"Steak",
   "ingredients":["beef","salt"],
   "instructions":"Baste in the oven",
   "imageURL":"None",
   "cookingTime":20,
   "userOwner":"647e3e5904f1b808d5aaf52e"
}


