POST http://localhost:3001/auth/register 
Content-Type: application/json

{
   "username":"Mydawg",
   "password":"socool1234"
}

###
POST http://localhost:3001/auth/login
Content-Type: application/json

{
   "username":"Mydawg",
   "password":"socool1234"
}

